import type { Metadata } from "next";
import "../globals.css";
import AdminLayout from "@/components/admin/sidebar-layout-provider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
    title: "Curiosity AI",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" data-theme="forest">
            <body>
                <ClerkProvider>
                    <AdminLayout>{children}</AdminLayout>
                </ClerkProvider>
            </body>
        </html>
    );
}
